### ISSUE TITLE
Something wrong during Installation

### ISSUE THREAD

**Issue by Xiangao2018** [mulder21c/hexo-theme-amorfati#2]
hey:
    I am interested in your hexo theme, I follow your read me installtation,  but when i type "hexo server" , something wrong

```
rs:blog (master)$ hexo server -p 4001
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: ENOSPC: System limit for number of file watchers reached, watch '/home/rs/Documents/blog/themes/amorfati/node_modules/lodash/_createInverter.js'
    at FSWatcher.start (internal/fs/watchers.js:168:26)
    at Object.watch (fs.js:1293:11)
    at createFsWatchInstance (/home/rs/Documents/blog/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/rs/Documents/blog/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/rs/Documents/blog/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/rs/Documents/blog/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/rs/Documents/blog/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqCallback.oncomplete (fs.js:149:5)

```

Ubuntu system 16.04 
nodejs -v: v4.2.6
npm -v: 6.9.0

**Comment by mulder21c** [comment]
Ummm...

Could you please try [ENOSPC Error (Linux)](https://hexo.io/docs/troubleshooting.html#ENOSPC-Error-Linux)?  &mdash; Trouble shooting provided by hexo

**Comment by Xiangao2018** [comment]
i run successful after run follow cmd 

```
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

thank you very much

**Comment by mulder21c** [comment]
@Rsenjoyer Oh! It sounds good. Enjoy~ :)
