### ISSUE TITLE
Fresh install error

### ISSUE THREAD

**Issue by lgwapnitsky** [mulder21c/hexo-theme-amorfati#9]
configured on Ubuntu 20 with node.js 14

When I switch to this theme and run hexo serve, I receive the following:

`Unhandled rejection TypeError: /home/lgwapnitsky/lgw/themes/amorfati/layout/elements/head/opengraph.pug:21
    19|     meta_description = page.seo && page.seo.description || excerpt || config.description || ``;
    20|   meta_description = strip_html(meta_description).replace(/\n/g, ' ').replace(/^\s*\t*|\s*\t*$/g, '');
  > 21| -
    22|   const openGraph = open_graph({
    23|     description: strip_html(meta_description).replace(/\n/g, ''),
    24|     author: page.seo && page.seo.author || config.author,

Cannot read property 'compact' of undefined
    at eval (eval at wrap (/home/lgwapnitsky/lgw/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:222:12)
    at template (eval at wrap (/home/lgwapnitsky/lgw/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1437:177)
    at _View._compiled (/home/lgwapnitsky/lgw/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/home/lgwapnitsky/lgw/node_modules/hexo/lib/theme/view.js:39:17)
    at /home/lgwapnitsky/lgw/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/home/lgwapnitsky/lgw/node_modules/bluebird/js/release/util.js:16:23)
    at /home/lgwapnitsky/lgw/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/lgwapnitsky/lgw/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:481:10)
    at resume_ (_stream_readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
`

**Comment by mulder21c** [comment]
@lgwapnitsky oh, I'm so sorry, I saw the issue late.
Do you use Hexo version 5.x ? 
This theme supports version 4, and I have found similar problems in version 5.
I'm going to make a new theme to respond to version 5, but I don't know when it's going to proceed yet.

**Comment by lgwapnitsky** [comment]
No worries
